--------------------------------------------------------
--  DDL for Table ALLAS
--------------------------------------------------------

  CREATE TABLE "C##TESZT"."ALLAS" 
   (	"ID" NUMBER(10,0), 
	"ALLAS_NEVE" VARCHAR2(800 CHAR), 
	"ALLAS_LEIRASA" CLOB, 
	"MUNKAKOR_ID" NUMBER(10,0), 
	"HIRDETO_ID" NUMBER(10,0), 
	"KAPCSOLAT_ID" NUMBER(10,0), 
	"DIAK_VALLALHATJA" NUMBER(10,0), 
	"HELYSZIN_ID" NUMBER(10,0), 
	"KEZDES_IDOPONTJA" TIMESTAMP (6), 
	"BEREZES" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("ALLAS_LEIRASA") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW 4000 CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 262144 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
