--------------------------------------------------------
--  Constraints for Table ALLAS
--------------------------------------------------------

  ALTER TABLE "C##TESZT"."ALLAS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "C##TESZT"."ALLAS" MODIFY ("ALLAS_NEVE" NOT NULL ENABLE);
  ALTER TABLE "C##TESZT"."ALLAS" MODIFY ("ALLAS_LEIRASA" NOT NULL ENABLE);
  ALTER TABLE "C##TESZT"."ALLAS" MODIFY ("HIRDETO_ID" NOT NULL ENABLE);
  ALTER TABLE "C##TESZT"."ALLAS" MODIFY ("KAPCSOLAT_ID" NOT NULL ENABLE);
  ALTER TABLE "C##TESZT"."ALLAS" MODIFY ("DIAK_VALLALHATJA" NOT NULL ENABLE);
  ALTER TABLE "C##TESZT"."ALLAS" MODIFY ("KEZDES_IDOPONTJA" NOT NULL ENABLE);
  ALTER TABLE "C##TESZT"."ALLAS" MODIFY ("BEREZES" NOT NULL ENABLE);
