DROP TABLE IF EXISTS munkakor;
CREATE TABLE munkakor(
   id                   INTEGER  NOT NULL PRIMARY KEY 
  ,allas_tipusa         VARCHAR(50) NOT NULL
  ,szuksegse_vegzettseg VARCHAR(50) NOT NULL
  ,egyeb_feltetelek_id  INTEGER 
);
INSERT INTO munkakor(id,allas_tipusa,szuksegse_vegzettseg,egyeb_feltetelek_id) VALUES (1,'Fizikai','rettsgi',NULL);
INSERT INTO munkakor(id,allas_tipusa,szuksegse_vegzettseg,egyeb_feltetelek_id) VALUES (2,'Fizikai','rettsgi',27);
INSERT INTO munkakor(id,allas_tipusa,szuksegse_vegzettseg,egyeb_feltetelek_id) VALUES (3,'Fizikai','rettsgi',21);
INSERT INTO munkakor(id,allas_tipusa,szuksegse_vegzettseg,egyeb_feltetelek_id) VALUES (4,'Fizikai','rettsgi',46);
INSERT INTO munkakor(id,allas_tipusa,szuksegse_vegzettseg,egyeb_feltetelek_id) VALUES (5,'Fizikai','rettsgi',47);
INSERT INTO munkakor(id,allas_tipusa,szuksegse_vegzettseg,egyeb_feltetelek_id) VALUES (6,'Fizikai','8 ltalnos',NULL);
INSERT INTO munkakor(id,allas_tipusa,szuksegse_vegzettseg,egyeb_feltetelek_id) VALUES (7,'Fizikai','8 ltalnos',1);
INSERT INTO munkakor(id,allas_tipusa,szuksegse_vegzettseg,egyeb_feltetelek_id) VALUES (8,'Fizikai','8 ltalnos',22);
INSERT INTO munkakor(id,allas_tipusa,szuksegse_vegzettseg,egyeb_feltetelek_id) VALUES (9,'Fizikai','8 ltalnos',31);
INSERT INTO munkakor(id,allas_tipusa,szuksegse_vegzettseg,egyeb_feltetelek_id) VALUES (10,'Fizikai','8 ltalnos',15);
INSERT INTO munkakor(id,allas_tipusa,szuksegse_vegzettseg,egyeb_feltetelek_id) VALUES (11,'Fizikai','8 ltalnos',38);
INSERT INTO munkakor(id,allas_tipusa,szuksegse_vegzettseg,egyeb_feltetelek_id) VALUES (12,'Fizikai','8 ltalnos',10);
INSERT INTO munkakor(id,allas_tipusa,szuksegse_vegzettseg,egyeb_feltetelek_id) VALUES (13,'Fizikai','8 ltalnos',37);
INSERT INTO munkakor(id,allas_tipusa,szuksegse_vegzettseg,egyeb_feltetelek_id) VALUES (14,'Irodai','8 ltalnos',35);
INSERT INTO munkakor(id,allas_tipusa,szuksegse_vegzettseg,egyeb_feltetelek_id) VALUES (15,'Irodai','8 ltalnos',NULL);
INSERT INTO munkakor(id,allas_tipusa,szuksegse_vegzettseg,egyeb_feltetelek_id) VALUES (16,'Irodai','8 ltalnos',7);
INSERT INTO munkakor(id,allas_tipusa,szuksegse_vegzettseg,egyeb_feltetelek_id) VALUES (17,'Irodai','rettsgi',NULL);
INSERT INTO munkakor(id,allas_tipusa,szuksegse_vegzettseg,egyeb_feltetelek_id) VALUES (18,'Irodai','rettsgi',4);
INSERT INTO munkakor(id,allas_tipusa,szuksegse_vegzettseg,egyeb_feltetelek_id) VALUES (19,'Irodai','rettsgi',2);
INSERT INTO munkakor(id,allas_tipusa,szuksegse_vegzettseg,egyeb_feltetelek_id) VALUES (20,'Irodai','rettsgi',26);
INSERT INTO munkakor(id,allas_tipusa,szuksegse_vegzettseg,egyeb_feltetelek_id) VALUES (21,'Irodai','rettsgi',8);
INSERT INTO munkakor(id,allas_tipusa,szuksegse_vegzettseg,egyeb_feltetelek_id) VALUES (22,'Irodai','rettsgi',43);
INSERT INTO munkakor(id,allas_tipusa,szuksegse_vegzettseg,egyeb_feltetelek_id) VALUES (23,'Irodai','rettsgi',16);
INSERT INTO munkakor(id,allas_tipusa,szuksegse_vegzettseg,egyeb_feltetelek_id) VALUES (24,'Irodai','Diploma',44);
INSERT INTO munkakor(id,allas_tipusa,szuksegse_vegzettseg,egyeb_feltetelek_id) VALUES (25,'Irodai','Diploma',NULL);
INSERT INTO munkakor(id,allas_tipusa,szuksegse_vegzettseg,egyeb_feltetelek_id) VALUES (26,'Irodai','Diploma',41);
INSERT INTO munkakor(id,allas_tipusa,szuksegse_vegzettseg,egyeb_feltetelek_id) VALUES (27,'Irodai','Diploma',33);
INSERT INTO munkakor(id,allas_tipusa,szuksegse_vegzettseg,egyeb_feltetelek_id) VALUES (28,'Irodai','Diploma',34);
INSERT INTO munkakor(id,allas_tipusa,szuksegse_vegzettseg,egyeb_feltetelek_id) VALUES (29,'Irodai','Diploma',39);
INSERT INTO munkakor(id,allas_tipusa,szuksegse_vegzettseg,egyeb_feltetelek_id) VALUES (30,'Fizikai','Diploma',12);
INSERT INTO munkakor(id,allas_tipusa,szuksegse_vegzettseg,egyeb_feltetelek_id) VALUES (31,'Fizikai','Diploma',NULL);
INSERT INTO munkakor(id,allas_tipusa,szuksegse_vegzettseg,egyeb_feltetelek_id) VALUES (32,'Fizikai','Diploma',18);
INSERT INTO munkakor(id,allas_tipusa,szuksegse_vegzettseg,egyeb_feltetelek_id) VALUES (33,'Fizikai','Diploma',9);
INSERT INTO munkakor(id,allas_tipusa,szuksegse_vegzettseg,egyeb_feltetelek_id) VALUES (34,'Fizikai','Diploma',6);
INSERT INTO munkakor(id,allas_tipusa,szuksegse_vegzettseg,egyeb_feltetelek_id) VALUES (35,'Fizikai','Diploma',11);
INSERT INTO munkakor(id,allas_tipusa,szuksegse_vegzettseg,egyeb_feltetelek_id) VALUES (36,'Fizikai','Diploma',45);
INSERT INTO munkakor(id,allas_tipusa,szuksegse_vegzettseg,egyeb_feltetelek_id) VALUES (37,'Fizikai','Diploma',28);
INSERT INTO munkakor(id,allas_tipusa,szuksegse_vegzettseg,egyeb_feltetelek_id) VALUES (38,'Fizikai','Diploma',23);
INSERT INTO munkakor(id,allas_tipusa,szuksegse_vegzettseg,egyeb_feltetelek_id) VALUES (39,'Fizikai','Diploma',32);
INSERT INTO munkakor(id,allas_tipusa,szuksegse_vegzettseg,egyeb_feltetelek_id) VALUES (40,'Fizikai','Diploma',17);
INSERT INTO munkakor(id,allas_tipusa,szuksegse_vegzettseg,egyeb_feltetelek_id) VALUES (41,'Fizikai','Diploma',14);
INSERT INTO munkakor(id,allas_tipusa,szuksegse_vegzettseg,egyeb_feltetelek_id) VALUES (42,'Fizikai','8 ltalnos',24);
INSERT INTO munkakor(id,allas_tipusa,szuksegse_vegzettseg,egyeb_feltetelek_id) VALUES (43,'Fizikai','8 ltalnos',36);
INSERT INTO munkakor(id,allas_tipusa,szuksegse_vegzettseg,egyeb_feltetelek_id) VALUES (44,'Fizikai','8 ltalnos',40);
INSERT INTO munkakor(id,allas_tipusa,szuksegse_vegzettseg,egyeb_feltetelek_id) VALUES (45,'Fizikai','8 ltalnos',5);
INSERT INTO munkakor(id,allas_tipusa,szuksegse_vegzettseg,egyeb_feltetelek_id) VALUES (46,'Fizikai','8 ltalnos',29);
INSERT INTO munkakor(id,allas_tipusa,szuksegse_vegzettseg,egyeb_feltetelek_id) VALUES (47,'Irodai','rettsgi',20);
INSERT INTO munkakor(id,allas_tipusa,szuksegse_vegzettseg,egyeb_feltetelek_id) VALUES (48,'Irodai','rettsgi',42);
INSERT INTO munkakor(id,allas_tipusa,szuksegse_vegzettseg,egyeb_feltetelek_id) VALUES (49,'Irodai','rettsgi',30);
INSERT INTO munkakor(id,allas_tipusa,szuksegse_vegzettseg,egyeb_feltetelek_id) VALUES (50,'Irodai','Diploma',13);
INSERT INTO munkakor(id,allas_tipusa,szuksegse_vegzettseg,egyeb_feltetelek_id) VALUES (51,'Irodai','Diploma',19);
INSERT INTO munkakor(id,allas_tipusa,szuksegse_vegzettseg,egyeb_feltetelek_id) VALUES (52,'Irodai','Diploma',3);
INSERT INTO munkakor(id,allas_tipusa,szuksegse_vegzettseg,egyeb_feltetelek_id) VALUES (53,'Irodai','Diploma',25);
INSERT INTO munkakor(id,allas_tipusa,szuksegse_vegzettseg,egyeb_feltetelek_id) VALUES (54,'Irodai','Diploma',48);
