CREATE TABLE mytable(
   ID                   INTEGER  NOT NULL PRIMARY KEY 
  ,Állás_típusa         VARCHAR(7) NOT NULL
  ,Szükséges_végzettség VARCHAR(11) NOT NULL
  ,Egyéb_feltételek_id  VARCHAR(30)
);
INSERT INTO mytable(ID,Állás_típusa,Szükséges_végzettség,Egyéb_feltételek_id) VALUES (1,'Fizikai','Érettségi',NULL);
INSERT INTO mytable(ID,Állás_típusa,Szükséges_végzettség,Egyéb_feltételek_id) VALUES (2,'Fizikai','Érettségi',NULL);
INSERT INTO mytable(ID,Állás_típusa,Szükséges_végzettség,Egyéb_feltételek_id) VALUES (3,'Fizikai','Érettségi',NULL);
INSERT INTO mytable(ID,Állás_típusa,Szükséges_végzettség,Egyéb_feltételek_id) VALUES (4,'Fizikai','Érettségi',NULL);
INSERT INTO mytable(ID,Állás_típusa,Szükséges_végzettség,Egyéb_feltételek_id) VALUES (5,'Fizikai','Érettségi',NULL);
INSERT INTO mytable(ID,Állás_típusa,Szükséges_végzettség,Egyéb_feltételek_id) VALUES (6,'Fizikai','Érettségi',NULL);
INSERT INTO mytable(ID,Állás_típusa,Szükséges_végzettség,Egyéb_feltételek_id) VALUES (7,'Fizikai','Érettségi',NULL);
INSERT INTO mytable(ID,Állás_típusa,Szükséges_végzettség,Egyéb_feltételek_id) VALUES (8,'Fizikai','Érettségi',NULL);
INSERT INTO mytable(ID,Állás_típusa,Szükséges_végzettség,Egyéb_feltételek_id) VALUES (9,'Fizikai','Érettségi',NULL);
INSERT INTO mytable(ID,Állás_típusa,Szükséges_végzettség,Egyéb_feltételek_id) VALUES (10,'Fizikai','Érettségi',NULL);
INSERT INTO mytable(ID,Állás_típusa,Szükséges_végzettség,Egyéb_feltételek_id) VALUES (11,'Fizikai','8 általános',NULL);
INSERT INTO mytable(ID,Állás_típusa,Szükséges_végzettség,Egyéb_feltételek_id) VALUES (12,'Fizikai','8 általános',NULL);
INSERT INTO mytable(ID,Állás_típusa,Szükséges_végzettség,Egyéb_feltételek_id) VALUES (13,'Fizikai','8 általános',NULL);
INSERT INTO mytable(ID,Állás_típusa,Szükséges_végzettség,Egyéb_feltételek_id) VALUES (14,'Fizikai','8 általános',NULL);
INSERT INTO mytable(ID,Állás_típusa,Szükséges_végzettség,Egyéb_feltételek_id) VALUES (15,'Fizikai','8 általános',NULL);
INSERT INTO mytable(ID,Állás_típusa,Szükséges_végzettség,Egyéb_feltételek_id) VALUES (16,'Fizikai','8 általános',NULL);
INSERT INTO mytable(ID,Állás_típusa,Szükséges_végzettség,Egyéb_feltételek_id) VALUES (17,'Fizikai','8 általános',NULL);
INSERT INTO mytable(ID,Állás_típusa,Szükséges_végzettség,Egyéb_feltételek_id) VALUES (18,'Fizikai','8 általános',NULL);
INSERT INTO mytable(ID,Állás_típusa,Szükséges_végzettség,Egyéb_feltételek_id) VALUES (19,'Fizikai','8 általános',NULL);
INSERT INTO mytable(ID,Állás_típusa,Szükséges_végzettség,Egyéb_feltételek_id) VALUES (20,'Fizikai','8 általános',NULL);
INSERT INTO mytable(ID,Állás_típusa,Szükséges_végzettség,Egyéb_feltételek_id) VALUES (21,'Fizikai','8 általános',NULL);
INSERT INTO mytable(ID,Állás_típusa,Szükséges_végzettség,Egyéb_feltételek_id) VALUES (22,'Fizikai','8 általános',NULL);
INSERT INTO mytable(ID,Állás_típusa,Szükséges_végzettség,Egyéb_feltételek_id) VALUES (23,'Fizikai','8 általános',NULL);
INSERT INTO mytable(ID,Állás_típusa,Szükséges_végzettség,Egyéb_feltételek_id) VALUES (24,'Fizikai','8 általános',NULL);
INSERT INTO mytable(ID,Állás_típusa,Szükséges_végzettség,Egyéb_feltételek_id) VALUES (25,'Irodai','8 általános',NULL);
INSERT INTO mytable(ID,Állás_típusa,Szükséges_végzettség,Egyéb_feltételek_id) VALUES (26,'Irodai','8 általános',NULL);
INSERT INTO mytable(ID,Állás_típusa,Szükséges_végzettség,Egyéb_feltételek_id) VALUES (27,'Irodai','8 általános',NULL);
INSERT INTO mytable(ID,Állás_típusa,Szükséges_végzettség,Egyéb_feltételek_id) VALUES (28,'Irodai','8 általános',NULL);
INSERT INTO mytable(ID,Állás_típusa,Szükséges_végzettség,Egyéb_feltételek_id) VALUES (29,'Irodai','Érettségi',NULL);
INSERT INTO mytable(ID,Állás_típusa,Szükséges_végzettség,Egyéb_feltételek_id) VALUES (30,'Irodai','Érettségi',NULL);
INSERT INTO mytable(ID,Állás_típusa,Szükséges_végzettség,Egyéb_feltételek_id) VALUES (31,'Irodai','Érettségi',NULL);
INSERT INTO mytable(ID,Állás_típusa,Szükséges_végzettség,Egyéb_feltételek_id) VALUES (32,'Irodai','Érettségi',NULL);
INSERT INTO mytable(ID,Állás_típusa,Szükséges_végzettség,Egyéb_feltételek_id) VALUES (33,'Irodai','Érettségi',NULL);
INSERT INTO mytable(ID,Állás_típusa,Szükséges_végzettség,Egyéb_feltételek_id) VALUES (34,'Irodai','Érettségi',NULL);
INSERT INTO mytable(ID,Állás_típusa,Szükséges_végzettség,Egyéb_feltételek_id) VALUES (35,'Irodai','Érettségi',NULL);
INSERT INTO mytable(ID,Állás_típusa,Szükséges_végzettség,Egyéb_feltételek_id) VALUES (36,'Irodai','Érettségi',NULL);
INSERT INTO mytable(ID,Állás_típusa,Szükséges_végzettség,Egyéb_feltételek_id) VALUES (37,'Irodai','Érettségi',NULL);
INSERT INTO mytable(ID,Állás_típusa,Szükséges_végzettség,Egyéb_feltételek_id) VALUES (38,'Irodai','Érettségi',NULL);
INSERT INTO mytable(ID,Állás_típusa,Szükséges_végzettség,Egyéb_feltételek_id) VALUES (39,'Irodai','Érettségi',NULL);
INSERT INTO mytable(ID,Állás_típusa,Szükséges_végzettség,Egyéb_feltételek_id) VALUES (40,'Irodai','Érettségi',NULL);
INSERT INTO mytable(ID,Állás_típusa,Szükséges_végzettség,Egyéb_feltételek_id) VALUES (41,'Irodai','Diploma',NULL);
INSERT INTO mytable(ID,Állás_típusa,Szükséges_végzettség,Egyéb_feltételek_id) VALUES (42,'Irodai','Diploma',NULL);
INSERT INTO mytable(ID,Állás_típusa,Szükséges_végzettség,Egyéb_feltételek_id) VALUES (43,'Irodai','Diploma',NULL);
INSERT INTO mytable(ID,Állás_típusa,Szükséges_végzettség,Egyéb_feltételek_id) VALUES (44,'Irodai','Diploma',NULL);
INSERT INTO mytable(ID,Állás_típusa,Szükséges_végzettség,Egyéb_feltételek_id) VALUES (45,'Irodai','Diploma',NULL);
INSERT INTO mytable(ID,Állás_típusa,Szükséges_végzettség,Egyéb_feltételek_id) VALUES (46,'Irodai','Diploma',NULL);
INSERT INTO mytable(ID,Állás_típusa,Szükséges_végzettség,Egyéb_feltételek_id) VALUES (47,'Irodai','Diploma',NULL);
INSERT INTO mytable(ID,Állás_típusa,Szükséges_végzettség,Egyéb_feltételek_id) VALUES (48,'Irodai','Diploma',NULL);
INSERT INTO mytable(ID,Állás_típusa,Szükséges_végzettség,Egyéb_feltételek_id) VALUES (49,'Irodai','Diploma',NULL);
INSERT INTO mytable(ID,Állás_típusa,Szükséges_végzettség,Egyéb_feltételek_id) VALUES (50,'Fizikai','Diploma',NULL);
INSERT INTO mytable(ID,Állás_típusa,Szükséges_végzettség,Egyéb_feltételek_id) VALUES (51,'Fizikai','Diploma',NULL);
INSERT INTO mytable(ID,Állás_típusa,Szükséges_végzettség,Egyéb_feltételek_id) VALUES (52,'Fizikai','Diploma',NULL);
INSERT INTO mytable(ID,Állás_típusa,Szükséges_végzettség,Egyéb_feltételek_id) VALUES (53,'Fizikai','Diploma',NULL);
INSERT INTO mytable(ID,Állás_típusa,Szükséges_végzettség,Egyéb_feltételek_id) VALUES (54,'Fizikai','Diploma',NULL);
INSERT INTO mytable(ID,Állás_típusa,Szükséges_végzettség,Egyéb_feltételek_id) VALUES (55,'Fizikai','Diploma',NULL);
INSERT INTO mytable(ID,Állás_típusa,Szükséges_végzettség,Egyéb_feltételek_id) VALUES (56,'Fizikai','Diploma',NULL);
INSERT INTO mytable(ID,Állás_típusa,Szükséges_végzettség,Egyéb_feltételek_id) VALUES (57,'Fizikai','Diploma',NULL);
INSERT INTO mytable(ID,Állás_típusa,Szükséges_végzettség,Egyéb_feltételek_id) VALUES (58,'Fizikai','Diploma',NULL);
INSERT INTO mytable(ID,Állás_típusa,Szükséges_végzettség,Egyéb_feltételek_id) VALUES (59,'Fizikai','Diploma',NULL);
INSERT INTO mytable(ID,Állás_típusa,Szükséges_végzettség,Egyéb_feltételek_id) VALUES (60,'Fizikai','Diploma',NULL);
INSERT INTO mytable(ID,Állás_típusa,Szükséges_végzettség,Egyéb_feltételek_id) VALUES (61,'Fizikai','Diploma',NULL);
INSERT INTO mytable(ID,Állás_típusa,Szükséges_végzettség,Egyéb_feltételek_id) VALUES (62,'Fizikai','Diploma',NULL);
INSERT INTO mytable(ID,Állás_típusa,Szükséges_végzettség,Egyéb_feltételek_id) VALUES (63,'Fizikai','Diploma',NULL);
INSERT INTO mytable(ID,Állás_típusa,Szükséges_végzettség,Egyéb_feltételek_id) VALUES (64,'Fizikai','Diploma',NULL);
INSERT INTO mytable(ID,Állás_típusa,Szükséges_végzettség,Egyéb_feltételek_id) VALUES (65,'Fizikai','Diploma',NULL);
INSERT INTO mytable(ID,Állás_típusa,Szükséges_végzettség,Egyéb_feltételek_id) VALUES (66,'Fizikai','Diploma',NULL);
INSERT INTO mytable(ID,Állás_típusa,Szükséges_végzettség,Egyéb_feltételek_id) VALUES (67,'Fizikai','Diploma',NULL);
INSERT INTO mytable(ID,Állás_típusa,Szükséges_végzettség,Egyéb_feltételek_id) VALUES (68,'Fizikai','Diploma',NULL);
INSERT INTO mytable(ID,Állás_típusa,Szükséges_végzettség,Egyéb_feltételek_id) VALUES (69,'Fizikai','Diploma',NULL);
INSERT INTO mytable(ID,Állás_típusa,Szükséges_végzettség,Egyéb_feltételek_id) VALUES (70,'Fizikai','8 általános',NULL);
INSERT INTO mytable(ID,Állás_típusa,Szükséges_végzettség,Egyéb_feltételek_id) VALUES (71,'Fizikai','8 általános',NULL);
INSERT INTO mytable(ID,Állás_típusa,Szükséges_végzettség,Egyéb_feltételek_id) VALUES (72,'Fizikai','8 általános',NULL);
INSERT INTO mytable(ID,Állás_típusa,Szükséges_végzettség,Egyéb_feltételek_id) VALUES (73,'Fizikai','8 általános',NULL);
INSERT INTO mytable(ID,Állás_típusa,Szükséges_végzettség,Egyéb_feltételek_id) VALUES (74,'Fizikai','8 általános',NULL);
INSERT INTO mytable(ID,Állás_típusa,Szükséges_végzettség,Egyéb_feltételek_id) VALUES (75,'Fizikai','8 általános',NULL);
INSERT INTO mytable(ID,Állás_típusa,Szükséges_végzettség,Egyéb_feltételek_id) VALUES (76,'Irodai','8 általános',NULL);
INSERT INTO mytable(ID,Állás_típusa,Szükséges_végzettség,Egyéb_feltételek_id) VALUES (77,'Irodai','8 általános',NULL);
INSERT INTO mytable(ID,Állás_típusa,Szükséges_végzettség,Egyéb_feltételek_id) VALUES (78,'Irodai','Érettségi',NULL);
INSERT INTO mytable(ID,Állás_típusa,Szükséges_végzettség,Egyéb_feltételek_id) VALUES (79,'Irodai','Érettségi',NULL);
INSERT INTO mytable(ID,Állás_típusa,Szükséges_végzettség,Egyéb_feltételek_id) VALUES (80,'Irodai','Érettségi',NULL);
INSERT INTO mytable(ID,Állás_típusa,Szükséges_végzettség,Egyéb_feltételek_id) VALUES (81,'Irodai','Érettségi',NULL);
INSERT INTO mytable(ID,Állás_típusa,Szükséges_végzettség,Egyéb_feltételek_id) VALUES (82,'Irodai','Érettségi',NULL);
INSERT INTO mytable(ID,Állás_típusa,Szükséges_végzettség,Egyéb_feltételek_id) VALUES (83,'Irodai','Érettségi',NULL);
INSERT INTO mytable(ID,Állás_típusa,Szükséges_végzettség,Egyéb_feltételek_id) VALUES (84,'Irodai','Érettségi',NULL);
INSERT INTO mytable(ID,Állás_típusa,Szükséges_végzettség,Egyéb_feltételek_id) VALUES (85,'Irodai','Érettségi',NULL);
INSERT INTO mytable(ID,Állás_típusa,Szükséges_végzettség,Egyéb_feltételek_id) VALUES (86,'Irodai','Érettségi',NULL);
INSERT INTO mytable(ID,Állás_típusa,Szükséges_végzettség,Egyéb_feltételek_id) VALUES (87,'Irodai','Érettségi',NULL);
INSERT INTO mytable(ID,Állás_típusa,Szükséges_végzettség,Egyéb_feltételek_id) VALUES (88,'Irodai','Érettségi',NULL);
INSERT INTO mytable(ID,Állás_típusa,Szükséges_végzettség,Egyéb_feltételek_id) VALUES (89,'Irodai','Érettségi',NULL);
INSERT INTO mytable(ID,Állás_típusa,Szükséges_végzettség,Egyéb_feltételek_id) VALUES (90,'Irodai','Diploma',NULL);
INSERT INTO mytable(ID,Állás_típusa,Szükséges_végzettség,Egyéb_feltételek_id) VALUES (91,'Irodai','Diploma',NULL);
INSERT INTO mytable(ID,Állás_típusa,Szükséges_végzettség,Egyéb_feltételek_id) VALUES (92,'Irodai','Diploma',NULL);
INSERT INTO mytable(ID,Állás_típusa,Szükséges_végzettség,Egyéb_feltételek_id) VALUES (93,'Irodai','Diploma',NULL);
INSERT INTO mytable(ID,Állás_típusa,Szükséges_végzettség,Egyéb_feltételek_id) VALUES (94,'Irodai','Diploma',NULL);
INSERT INTO mytable(ID,Állás_típusa,Szükséges_végzettség,Egyéb_feltételek_id) VALUES (95,'Irodai','Diploma',NULL);
INSERT INTO mytable(ID,Állás_típusa,Szükséges_végzettség,Egyéb_feltételek_id) VALUES (96,'Irodai','Diploma',NULL);
INSERT INTO mytable(ID,Állás_típusa,Szükséges_végzettség,Egyéb_feltételek_id) VALUES (97,'Irodai','Diploma',NULL);
INSERT INTO mytable(ID,Állás_típusa,Szükséges_végzettség,Egyéb_feltételek_id) VALUES (98,'Irodai','Diploma',NULL);
INSERT INTO mytable(ID,Állás_típusa,Szükséges_végzettség,Egyéb_feltételek_id) VALUES (99,'Irodai','Diploma',NULL);
INSERT INTO mytable(ID,Állás_típusa,Szükséges_végzettség,Egyéb_feltételek_id) VALUES (100,'Irodai','Diploma',NULL);
