DROP TABLE IF EXISTS vegzettseg;
CREATE TABLE vegzettseg(
   id        INTEGER  NOT NULL PRIMARY KEY 
  ,nev       VARCHAR(50) NOT NULL
  ,intezmeny VARCHAR(50) NOT NULL
);
INSERT INTO vegzettseg(id,nev,intezmeny) VALUES (1,'Egyetem, BSC','Bridgeport International Academy');
INSERT INTO vegzettseg(id,nev,intezmeny) VALUES (2,'Technikum','Carmel Acadmey');
INSERT INTO vegzettseg(id,nev,intezmeny) VALUES (3,'Egyetem, MSC','Country Kids Club');
INSERT INTO vegzettseg(id,nev,intezmeny) VALUES (4,'Egyetem, MSC','Eagle Hill School');
INSERT INTO vegzettseg(id,nev,intezmeny) VALUES (5,'Technikum','Easton Country Day School');
INSERT INTO vegzettseg(id,nev,intezmeny) VALUES (6,'Egyetem, BSC','Fairfield County Sda School');
INSERT INTO vegzettseg(id,nev,intezmeny) VALUES (7,'Szakközépiskola','Fraser Woods Montessori School');
INSERT INTO vegzettseg(id,nev,intezmeny) VALUES (8,'Egyetem, BSC','Giant Steps Connecticut');
INSERT INTO vegzettseg(id,nev,intezmeny) VALUES (9,'Egyetem, BSC','Housatonic Valley Waldorf School');
INSERT INTO vegzettseg(id,nev,intezmeny) VALUES (10,'Gimnázium','Landmark Preschool');
INSERT INTO vegzettseg(id,nev,intezmeny) VALUES (11,'Egyetem, BSC','Abercorn International School');
INSERT INTO vegzettseg(id,nev,intezmeny) VALUES (12,'Gimnázium','Landmark Preschool');
INSERT INTO vegzettseg(id,nev,intezmeny) VALUES (13,'Szakközépiskola','Our Lady Of Grace Nursery School & Kindergarten');
INSERT INTO vegzettseg(id,nev,intezmeny) VALUES (14,'Egyetem, BSC','Our Lady Star Of The Sea School');
INSERT INTO vegzettseg(id,nev,intezmeny) VALUES (15,'Egyetem, MSC','Pierrepont School');
INSERT INTO vegzettseg(id,nev,intezmeny) VALUES (16,'Gimnázium','St Catherine Academy');
INSERT INTO vegzettseg(id,nev,intezmeny) VALUES (17,'Egyetem, MSC','St Jude School');
INSERT INTO vegzettseg(id,nev,intezmeny) VALUES (18,'Egyetem, BSC','St Mary School');
INSERT INTO vegzettseg(id,nev,intezmeny) VALUES (19,'Gimnázium','St Theresa School');
INSERT INTO vegzettseg(id,nev,intezmeny) VALUES (20,'Technikum','St Vincent''s Special Needs Services');
INSERT INTO vegzettseg(id,nev,intezmeny) VALUES (21,'Egyetem, MSC','The Canaan Ridge School');
INSERT INTO vegzettseg(id,nev,intezmeny) VALUES (22,'Technikum','The Greenwich Japanese School');
INSERT INTO vegzettseg(id,nev,intezmeny) VALUES (23,'Egyetem, MSC','The Stanwich School');
INSERT INTO vegzettseg(id,nev,intezmeny) VALUES (24,'Egyetem, BSC','Trinity Catholic Middle');
INSERT INTO vegzettseg(id,nev,intezmeny) VALUES (25,'Technikum','Villa Maria Education Center');
INSERT INTO vegzettseg(id,nev,intezmeny) VALUES (26,'Gimnázium','Whitby School');
INSERT INTO vegzettseg(id,nev,intezmeny) VALUES (27,'Egyetem, BSC','Wooster School');
INSERT INTO vegzettseg(id,nev,intezmeny) VALUES (28,'Egyetem, MSC','Little Wonders Of Baybrook Baptist');
INSERT INTO vegzettseg(id,nev,intezmeny) VALUES (29,'Technikum','Llano Christian Academy');
INSERT INTO vegzettseg(id,nev,intezmeny) VALUES (30,'Gimnázium','Logos Preparatory School');
INSERT INTO vegzettseg(id,nev,intezmeny) VALUES (31,'Egyetem, MSC','Macedonian Christian Academy');
INSERT INTO vegzettseg(id,nev,intezmeny) VALUES (32,'Technikum','Mainland Christian Academy Inc.');
INSERT INTO vegzettseg(id,nev,intezmeny) VALUES (33,'Technikum','Marble Falls First Baptist Christian School');
INSERT INTO vegzettseg(id,nev,intezmeny) VALUES (34,'Egyetem, BSC','Masterpiece Bilingual Academy');
INSERT INTO vegzettseg(id,nev,intezmeny) VALUES (35,'Egyetem, BSC','Mesorah High School For Girls');
INSERT INTO vegzettseg(id,nev,intezmeny) VALUES (36,'Egyetem, BSC','Midland Classical Academy');
INSERT INTO vegzettseg(id,nev,intezmeny) VALUES (37,'Egyetem, MSC','Montessori Country Day School');
INSERT INTO vegzettseg(id,nev,intezmeny) VALUES (38,'Gimnázium','Montessori School Of Sugar Land');
INSERT INTO vegzettseg(id,nev,intezmeny) VALUES (39,'Egyetem, BSC','Morning Star Academy');
INSERT INTO vegzettseg(id,nev,intezmeny) VALUES (40,'Egyetem, BSC','Mosaic Academy');
INSERT INTO vegzettseg(id,nev,intezmeny) VALUES (41,'Technikum','All Saints Catholic School');
INSERT INTO vegzettseg(id,nev,intezmeny) VALUES (42,'Gimnázium','American School For The Deaf');
INSERT INTO vegzettseg(id,nev,intezmeny) VALUES (43,'Egyetem, BSC','Brunswick School');
INSERT INTO vegzettseg(id,nev,intezmeny) VALUES (44,'Technikum','Catholic Academy Of Bridgeport/st Raphael Academy');
INSERT INTO vegzettseg(id,nev,intezmeny) VALUES (45,'Szakközépiskola','Christian Heritage School');
INSERT INTO vegzettseg(id,nev,intezmeny) VALUES (46,'Egyetem, BSC','Christian Life Academy');
INSERT INTO vegzettseg(id,nev,intezmeny) VALUES (47,'Gimnázium','Eagle Hill - Southport');
INSERT INTO vegzettseg(id,nev,intezmeny) VALUES (48,'Egyetem, MSC','Fairfield College Preparatory');
INSERT INTO vegzettseg(id,nev,intezmeny) VALUES (49,'Egyetem, BSC','Fairfield Country Day School');
INSERT INTO vegzettseg(id,nev,intezmeny) VALUES (50,'Egyetem, MSC','Great Beginnings Montessori School');
INSERT INTO vegzettseg(id,nev,intezmeny) VALUES (51,'Szakközépiskola','Greens Farms Academy');
INSERT INTO vegzettseg(id,nev,intezmeny) VALUES (52,'Gimnázium','Greenwich Catholic School');
INSERT INTO vegzettseg(id,nev,intezmeny) VALUES (53,'Gimnázium','Hudson Country Montessori School');
INSERT INTO vegzettseg(id,nev,intezmeny) VALUES (54,'Egyetem, MSC','Immaculate High School');
INSERT INTO vegzettseg(id,nev,intezmeny) VALUES (55,'Gimnázium','Immanuel Lutheran School');
INSERT INTO vegzettseg(id,nev,intezmeny) VALUES (56,'Gimnázium','Kolbe Cathedral High School');
INSERT INTO vegzettseg(id,nev,intezmeny) VALUES (57,'Technikum','Mooreland Hill School');
INSERT INTO vegzettseg(id,nev,intezmeny) VALUES (58,'Technikum','Notre Dame Catholic High School');
INSERT INTO vegzettseg(id,nev,intezmeny) VALUES (59,'Technikum','Pear Tree Point School');
INSERT INTO vegzettseg(id,nev,intezmeny) VALUES (60,'Technikum','St Andrew Academy');
INSERT INTO vegzettseg(id,nev,intezmeny) VALUES (61,'Technikum','St Ann Academy');
INSERT INTO vegzettseg(id,nev,intezmeny) VALUES (62,'Szakközépiskola','St Augustine Academy');
INSERT INTO vegzettseg(id,nev,intezmeny) VALUES (63,'Szakközépiskola','St Augustine School');
INSERT INTO vegzettseg(id,nev,intezmeny) VALUES (64,'Egyetem, MSC','St Catherine Of Siena School');
INSERT INTO vegzettseg(id,nev,intezmeny) VALUES (65,'Egyetem, BSC','St Cecilia Elementary School');
INSERT INTO vegzettseg(id,nev,intezmeny) VALUES (66,'Gimnázium','St Christopher School');
INSERT INTO vegzettseg(id,nev,intezmeny) VALUES (67,'Egyetem, BSC','St Gregory The Great School');
INSERT INTO vegzettseg(id,nev,intezmeny) VALUES (68,'Gimnázium','St James School');
INSERT INTO vegzettseg(id,nev,intezmeny) VALUES (69,'Egyetem, BSC','St Joseph Elementary School');
INSERT INTO vegzettseg(id,nev,intezmeny) VALUES (70,'Gimnázium','St Joseph High School');
INSERT INTO vegzettseg(id,nev,intezmeny) VALUES (71,'Egyetem, MSC','St Joseph School');
INSERT INTO vegzettseg(id,nev,intezmeny) VALUES (72,'Technikum','St Lawrence Elementary School');
INSERT INTO vegzettseg(id,nev,intezmeny) VALUES (73,'Gimnázium','St Mary Elementary School');
INSERT INTO vegzettseg(id,nev,intezmeny) VALUES (74,'Egyetem, BSC','St Rose Of Lima School');
INSERT INTO vegzettseg(id,nev,intezmeny) VALUES (75,'Szakközépiskola','St Thomas Aquinas Elementary School');
INSERT INTO vegzettseg(id,nev,intezmeny) VALUES (76,'Egyetem, MSC','The Children''s School');
INSERT INTO vegzettseg(id,nev,intezmeny) VALUES (77,'Egyetem, BSC','The Long Ridge School');
INSERT INTO vegzettseg(id,nev,intezmeny) VALUES (78,'Egyetem, MSC','The Mead School');
INSERT INTO vegzettseg(id,nev,intezmeny) VALUES (79,'Egyetem, BSC','The Montessori School');
INSERT INTO vegzettseg(id,nev,intezmeny) VALUES (80,'Szakközépiskola','Trinity Catholic High School');
INSERT INTO vegzettseg(id,nev,intezmeny) VALUES (81,'Egyetem, MSC','Assumption Early Learning Ce');
INSERT INTO vegzettseg(id,nev,intezmeny) VALUES (82,'Szakközépiskola','Avon Old Farms School');
INSERT INTO vegzettseg(id,nev,intezmeny) VALUES (83,'Technikum','Ben Bronz Academy');
INSERT INTO vegzettseg(id,nev,intezmeny) VALUES (84,'Szakközépiskola','Clinical Day School - Manchester Memorial Hospital');
INSERT INTO vegzettseg(id,nev,intezmeny) VALUES (85,'Gimnázium','Community Child Guidance Clinic');
INSERT INTO vegzettseg(id,nev,intezmeny) VALUES (86,'Gimnázium','Enfield Montessori School');
INSERT INTO vegzettseg(id,nev,intezmeny) VALUES (87,'Szakközépiskola','Ethel Walker School');
INSERT INTO vegzettseg(id,nev,intezmeny) VALUES (88,'Szakközépiskola','Gengras Center/univ Of St Joseph');
INSERT INTO vegzettseg(id,nev,intezmeny) VALUES (89,'Egyetem, BSC','Hartford Area Sda School');
INSERT INTO vegzettseg(id,nev,intezmeny) VALUES (90,'Egyetem, BSC','Hebrew High School Of New England');
INSERT INTO vegzettseg(id,nev,intezmeny) VALUES (91,'Egyetem, MSC','Heritage Christian School');
INSERT INTO vegzettseg(id,nev,intezmeny) VALUES (92,'Egyetem, MSC','Intensive Education Academy In');
INSERT INTO vegzettseg(id,nev,intezmeny) VALUES (93,'Egyetem, BSC','Kingswood-oxford School');
INSERT INTO vegzettseg(id,nev,intezmeny) VALUES (94,'Egyetem, MSC','Miss Porter''s School');
INSERT INTO vegzettseg(id,nev,intezmeny) VALUES (95,'Technikum','Montessori School Greater Hartford');
